pub enum Style {
    AlignContent,
    AlignItems,
    AlignSelf,
    Animation,
    AnimationDelay,
    AnimationDirection,
    AnimationDuration,
    AnimationFillMode,
    AnimationIterationCount,
    AnimationName,
    AnimationTimingFunction,
    AnimationPlayState,
    Background,
    BackgroundAttachment,
    BackgroundColor,
    BackgroundImage,
    BackgroundPosition,
    BackgroundRepeat,
    BackgroundClip,
    BackgroundOrigin,
    BackgroundSize,
    BackfaceVisibility,
    Border,
    BorderBottom,
    BorderBottomColor,
    BorderBottomLeftRadius,
    BorderBottomRightRadius,
    BorderBottomStyle,
    BorderBottomWidth,
    BorderCollapse,
    BorderColor,
    BorderImage,
    BorderImageOutset,
    BorderImageRepeat,
    BorderImageSlice,
    BorderImageSource,
    BorderImageWidth,
    BorderLeft,
    BorderLeftColor,
    BorderLeftStyle,
    BorderLeftWidth,
    BorderRadius,
    BorderRight,
    BorderRightColor,
    BorderRightStyle,
    BorderRightWidth,
    BorderSpacing,
    BorderStyle,
    BorderTop,
    BorderTopColor,
    BorderTopLeftRadius,
    BorderTopRightRadius,
    BorderTopStyle,
    BorderTopWidth,
    BorderWidth,
    Bottom,
    BoxDecorationBreak,
    BoxShadow,
    BoxSizing,
    CaptionSide,
    CaretColor,
    Clear,
    Clip,
    Color,
    ColumnCount,
    ColumnFill,
    ColumnGap,
    ColumnRule,
    ColumnRuleColor,
    ColumnRuleStyle,
    ColumnRuleWidth,
    Columns,
    ColumnSpan,
    ColumnWidth,
    Content,
    CounterIncrement,
    CounterReset,
    Cursor,
    Direction,
    Display,
    EmptyCells,
    Filter,
    Flex,
    FlexBasis,
    FlexDirection,
    FlexFlow,
    FlexGrow,
    FlexShrink,
    FlexWrap,
    CssFloat,
    Font,
    FontFamily,
    FontSize,
    FontStyle,
    FontVariant,
    FontWeight,
    FontSizeAdjust,
    FontStretch,
    HangingPunctuation,
    Height,
    Hyphens,
    Icon,
    ImageOrientation,
    Isolation,
    JustifyContent,
    Left,
    LetterSpacing,
    LineHeight,
    ListStyle,
    ListStyleImage,
    ListStylePosition,
    ListStyleType,
    Margin,
    MarginBottom,
    MarginLeft,
    MarginRight,
    MarginTop,
    MaxHeight,
    MaxWidth,
    MinHeight,
    MinWidth,
    NavDown,
    NavIndex,
    NavLeft,
    NavRight,
    NavUp,
    ObjectFit,
    ObjectPosition,
    Opacity,
    Order,
    Orphans,
    Outline,
    OutlineColor,
    OutlineOffset,
    OutlineStyle,
    OutlineWidth,
    Overflow,
    OverflowX,
    OverflowY,
    Padding,
    PaddingBottom,
    PaddingLeft,
    PaddingRight,
    PaddingTop,
    PageBreakAfter,
    PageBreakBefore,
    PageBreakInside,
    Perspective,
    PerspectiveOrigin,
    Position,
    Quotes,
    Resize,
    Right,
    ScrollBehavior,
    TableLayout,
    TabSize,
    TextAlign,
    TextAlignLast,
    TextDecoration,
    TextDecorationColor,
    TextDecorationLine,
    TextDecorationStyle,
    TextIndent,
    TextJustify,
    TextOverflow,
    TextShadow,
    TextTransform,
    Top,
    Transform,
    TransformOrigin,
    TransformStyle,
    Transition,
    TransitionProperty,
    TransitionDuration,
    TransitionTimingFunction,
    TransitionDelay,
    UnicodeBidi,
    UserSelect,
    VerticalAlign,
    Visibility,
    WhiteSpace,
    Width,
    WordBreak,
    WordSpacing,
    WordWrap,
    Widows,
    ZIndex,
}

pub(crate) fn get_style_str(typ: Style) -> &'static str {
    match typ {
        Style::AlignContent => "alignContent",
        Style::AlignItems => "alignItems",
        Style::AlignSelf => "alignSelf",
        Style::Animation => "animation",
        Style::AnimationDelay => "animationDelay",
        Style::AnimationDirection => "animationDirection",
        Style::AnimationDuration => "animationDuration",
        Style::AnimationFillMode => "animationFillMode",
        Style::AnimationIterationCount => "animationIterationCount",
        Style::AnimationName => "animationName",
        Style::AnimationTimingFunction => "animationTimingFunction",
        Style::AnimationPlayState => "animationPlayState",
        Style::Background => "background",
        Style::BackgroundAttachment => "backgroundAttachment",
        Style::BackgroundColor => "backgroundColor",
        Style::BackgroundImage => "backgroundImage",
        Style::BackgroundPosition => "backgroundPosition",
        Style::BackgroundRepeat => "backgroundRepeat",
        Style::BackgroundClip => "backgroundClip",
        Style::BackgroundOrigin => "backgroundOrigin",
        Style::BackgroundSize => "backgroundSize",
        Style::BackfaceVisibility => "backfaceVisibility",
        Style::Border => "border",
        Style::BorderBottom => "borderBottom",
        Style::BorderBottomColor => "borderBottomColor",
        Style::BorderBottomLeftRadius => "borderBottomLeftRadius",
        Style::BorderBottomRightRadius => "borderBottomRightRadius",
        Style::BorderBottomStyle => "borderBottomStyle",
        Style::BorderBottomWidth => "borderBottomWidth",
        Style::BorderCollapse => "borderCollapse",
        Style::BorderColor => "borderColor",
        Style::BorderImage => "borderImage",
        Style::BorderImageOutset => "borderImageOutset",
        Style::BorderImageRepeat => "borderImageRepeat",
        Style::BorderImageSlice => "borderImageSlice",
        Style::BorderImageSource => "borderImageSource",
        Style::BorderImageWidth => "borderImageWidth",
        Style::BorderLeft => "borderLeft",
        Style::BorderLeftColor => "borderLeftColor",
        Style::BorderLeftStyle => "borderLeftStyle",
        Style::BorderLeftWidth => "borderLeftWidth",
        Style::BorderRadius => "borderRadius",
        Style::BorderRight => "borderRight",
        Style::BorderRightColor => "borderRightColor",
        Style::BorderRightStyle => "borderRightStyle",
        Style::BorderRightWidth => "borderRightWidth",
        Style::BorderSpacing => "borderSpacing",
        Style::BorderStyle => "borderStyle",
        Style::BorderTop => "borderTop",
        Style::BorderTopColor => "borderTopColor",
        Style::BorderTopLeftRadius => "borderTopLeftRadius",
        Style::BorderTopRightRadius => "borderTopRightRadius",
        Style::BorderTopStyle => "borderTopStyle",
        Style::BorderTopWidth => "borderTopWidth",
        Style::BorderWidth => "borderWidth",
        Style::Bottom => "bottom",
        Style::BoxDecorationBreak => "boxDecorationBreak",
        Style::BoxShadow => "boxShadow",
        Style::BoxSizing => "boxSizing",
        Style::CaptionSide => "captionSide",
        Style::CaretColor => "caretColor",
        Style::Clear => "clear",
        Style::Clip => "clip",
        Style::Color => "color",
        Style::ColumnCount => "columnCount",
        Style::ColumnFill => "columnFill",
        Style::ColumnGap => "columnGap",
        Style::ColumnRule => "columnRule",
        Style::ColumnRuleColor => "columnRuleColor",
        Style::ColumnRuleStyle => "columnRuleStyle",
        Style::ColumnRuleWidth => "columnRuleWidth",
        Style::Columns => "columns",
        Style::ColumnSpan => "columnSpan",
        Style::ColumnWidth => "columnWidth",
        Style::Content => "content",
        Style::CounterIncrement => "counterIncrement",
        Style::CounterReset => "counterReset",
        Style::Cursor => "cursor",
        Style::Direction => "direction",
        Style::Display => "display",
        Style::EmptyCells => "emptyCells",
        Style::Filter => "filter",
        Style::Flex => "flex",
        Style::FlexBasis => "flexBasis",
        Style::FlexDirection => "flexDirection",
        Style::FlexFlow => "flexFlow",
        Style::FlexGrow => "flexGrow",
        Style::FlexShrink => "flexShrink",
        Style::FlexWrap => "flexWrap",
        Style::CssFloat => "cssFloat",
        Style::Font => "font",
        Style::FontFamily => "fontFamily",
        Style::FontSize => "fontSize",
        Style::FontStyle => "fontStyle",
        Style::FontVariant => "fontVariant",
        Style::FontWeight => "fontWeight",
        Style::FontSizeAdjust => "fontSizeAdjust",
        Style::FontStretch => "fontStretch",
        Style::HangingPunctuation => "hangingPunctuation",
        Style::Height => "height",
        Style::Hyphens => "hyphens",
        Style::Icon => "icon",
        Style::ImageOrientation => "imageOrientation",
        Style::Isolation => "isolation",
        Style::JustifyContent => "justifyContent",
        Style::Left => "left",
        Style::LetterSpacing => "letterSpacing",
        Style::LineHeight => "lineHeight",
        Style::ListStyle => "listStyle",
        Style::ListStyleImage => "listStyleImage",
        Style::ListStylePosition => "listStylePosition",
        Style::ListStyleType => "listStyleType",
        Style::Margin => "margin",
        Style::MarginBottom => "marginBottom",
        Style::MarginLeft => "marginLeft",
        Style::MarginRight => "marginRight",
        Style::MarginTop => "marginTop",
        Style::MaxHeight => "maxHeight",
        Style::MaxWidth => "maxWidth",
        Style::MinHeight => "minHeight",
        Style::MinWidth => "minWidth",
        Style::NavDown => "navDown",
        Style::NavIndex => "navIndex",
        Style::NavLeft => "navLeft",
        Style::NavRight => "navRight",
        Style::NavUp => "navUp",
        Style::ObjectFit => "objectFit",
        Style::ObjectPosition => "objectPosition",
        Style::Opacity => "opacity",
        Style::Order => "order",
        Style::Orphans => "orphans",
        Style::Outline => "outline",
        Style::OutlineColor => "outlineColor",
        Style::OutlineOffset => "outlineOffset",
        Style::OutlineStyle => "outlineStyle",
        Style::OutlineWidth => "outlineWidth",
        Style::Overflow => "overflow",
        Style::OverflowX => "overflowX",
        Style::OverflowY => "overflowY",
        Style::Padding => "padding",
        Style::PaddingBottom => "paddingBottom",
        Style::PaddingLeft => "paddingLeft",
        Style::PaddingRight => "paddingRight",
        Style::PaddingTop => "paddingTop",
        Style::PageBreakAfter => "pageBreakAfter",
        Style::PageBreakBefore => "pageBreakBefore",
        Style::PageBreakInside => "pageBreakInside",
        Style::Perspective => "perspective",
        Style::PerspectiveOrigin => "perspectiveOrigin",
        Style::Position => "position",
        Style::Quotes => "quotes",
        Style::Resize => "resize",
        Style::Right => "right",
        Style::ScrollBehavior => "scrollBehavior",
        Style::TableLayout => "tableLayout",
        Style::TabSize => "tabSize",
        Style::TextAlign => "textAlign",
        Style::TextAlignLast => "textAlignLast",
        Style::TextDecoration => "textDecoration",
        Style::TextDecorationColor => "textDecorationColor",
        Style::TextDecorationLine => "textDecorationLine",
        Style::TextDecorationStyle => "textDecorationStyle",
        Style::TextIndent => "textIndent",
        Style::TextJustify => "textJustify",
        Style::TextOverflow => "textOverflow",
        Style::TextShadow => "textShadow",
        Style::TextTransform => "textTransform",
        Style::Top => "top",
        Style::Transform => "transform",
        Style::TransformOrigin => "transformOrigin",
        Style::TransformStyle => "transformStyle",
        Style::Transition => "transition",
        Style::TransitionProperty => "transitionProperty",
        Style::TransitionDuration => "transitionDuration",
        Style::TransitionTimingFunction => "transitionTimingFunction",
        Style::TransitionDelay => "transitionDelay",
        Style::UnicodeBidi => "unicodeBidi",
        Style::UserSelect => "userSelect",
        Style::VerticalAlign => "verticalAlign",
        Style::Visibility => "visibility",
        Style::WhiteSpace => "whiteSpace",
        Style::Width => "width",
        Style::WordBreak => "wordBreak",
        Style::WordSpacing => "wordSpacing",
        Style::WordWrap => "wordWrap",
        Style::Widows => "widows",
        Style::ZIndex => "zIndex",
    }
}